- client/package.json
- pnpm-lock.yaml
- server/package.json
- #78 
- 실시간 통신을 위해 socket.io 및 DB용 mongoose 설치
- client : socket.io-client 설치
- server : @nestjs/websockets @nestjs/platform-socket.io socket.io@ nestJS/mongoose mongoose 설치
- package.json 변경
- 설치 버전
> Feature/#078 실시간 통신 및 db 환경 설정

- .prettierrc
- .vscode/settings.json
- client/index.html
- client/src/App.tsx
- client/src/main.tsx
- client/vite.config.ts
- eslint 에러안뜨는 버그 픽스
- eslint 에러안뜨는 버그 픽스
- settings.json 수정 -> eslint 에러 뜨도록
- prettier, eslint 충돌 해결
- pretter 설정 -> 모두 ""(쌍따옴표)로 포맷팅 되도록
- prettier 포맷팅 변경에 따라 파일 수정
- [정리 링크](https://abrupt-feta-9a9.notion.site/eslint-1359ff1b21c38052991ae0c765675fc6?pvs=4)
- prettier, eslint은 커밋 타입 chore로 하기로 했는데,, 깜빡했습니다.. 다음부터 조심하겠습니다..
- 해당 브랜치에서 확인 부탁드립니다! 
> Feature/#081 eslint 에러안뜨는 버그 픽스

- client/src/features/page/Page.tsx
- client/src/hooks/useMarkdownGrammer/handlers/backSpace.ts
- 클라이언트 빌드 에러 해결
- 안쓰는 useState 제거
- Editor 타입 명시 추가
> Feature/#107 클라이언트 빌드 에러 해결

- .github/workflows/deploy.yml
- .github/workflows/lint_and_test.yml
- .github/workflows/lint_and_unit_test.yml
- .gitignore
- docker-compose.debug.yml
- docker-compose.yml
- pnpm-lock.yaml
- server/jest-mongodb-config.ts
- server/jest.config.ts
- server/package.json
- server/src/app.module.spec.ts
- server/src/app.module.ts
- #085
- 모든 브랜치에서 Push할 때 기본적으로 lint와 unit test를 수행합니다.
- main 또는 dev 브랜치에 PR을 보내면 lint, unit test, docker build test를 수행합니다.
- 
> Feature/#085 PR 시 Docker 빌드 테스트 수행

- docker-compose.yml
- 빌드된 NestJS docker에서 JWT_SECRET 환경 변수를 읽지 못하는 문제 수정
- 빌드된 NestJS docker에서 JWT_SECRET 환경 변수를 읽지 못하는 문제 수정
> Hotfix/빌드된 NestJS docker에서 JWT_SECRET 환경 변수를 읽지 못하는 문제 수정

- docker-compose.yml
- certbot 인증서 관련 경로 수정
- SSL 인증서 발급 완료
- 이후 빌드에서 정상적으로 HTTPS 접속이 확인되면 설정이 끝납니다. 야호!
> Hotfix/certbot 인증서 관련 경로 수정 및 SSL 인증서 발급 완료

- pnpm-lock.yaml
- server/package.json
- server/src/app.controller.ts
- server/src/auth/auth.controller.ts
- server/src/auth/dto/user.dto.ts
- server/src/main.ts
- server/src/swagger/swagger.config.ts
- #149
- Swagger 환경 세팅
- API에 Swagger 적용
- Swagger API 문서는 개발 환경에서만 활성화됩니다.
- 주소 : localhost:3000/api-docs
> Feature/#149 Swagger API 문서 구축

- client/src/features/editor/Editor.style.ts
- client/src/features/editor/components/block/Block.animation.ts
- client/src/features/editor/components/block/Block.tsx
- client/src/features/editor/hooks/useBlockAnimtaion.ts
- 블록 애니메이션 구현
- 스크롤 위치에 따라 블록 애니메이션이 나타나도록 구현했습니다.
- block 속성중 animation: "highlight" 를 넣어주면 됩니다. 하이라이트 색상은 마음대로 했는데, 추천받습니다!
- 지금은 Hightlight 애니메이션만 적용됩니다. 글자단위는 아예 로직을 다르게해야해서 넘어갔습니다
- 블록 wave 애니메이션은 실패했습니다.. 추후 다시 해보겠습니다.
https://github.com/user-attachments/assets/82545f35-94db-4365-86d4-6d5dc2f36750
> Feature/#159 블록 애니메이션 구현

- .github/workflows/deploy.yml
- .github/workflows/lint_and_test.yml
- .github/workflows/lint_and_unit_test.yml
- docker-compose.yml
- #164
- 개발 과정에서 새로 추가된 환경 변수를 배포 환경에 적용합니다
- 추가된 환경 변수
- VITE_API_URL
- JWT_REFRESH_SECRET
> Feature/#164 배포 환경 변수 설정

- client/src/App.tsx
- client/src/stores/useUserStore.ts
- close #189
- accessToken도 세션스토리지에 저장
> Feature/#189 accessToken도 세션스토리지에 저장

- @noctaCrdt/Crdt.ts
- @noctaCrdt/Interfaces.ts
- @noctaCrdt/LinkedList.ts
- @noctaCrdt/Node.ts
- client/package.json
- client/src/constants/color.ts
- client/src/constants/option.ts
- client/src/features/editor/Editor.tsx
- client/src/features/editor/components/ColorOptionModal/BackgroundColorOptionModal.style.ts
- client/src/features/editor/components/ColorOptionModal/BackgroundColorOptionModal.tsx
- client/src/features/editor/components/ColorOptionModal/TextColorOptionModal.style.ts
- client/src/features/editor/components/ColorOptionModal/TextColorOptionModal.tsx
- client/src/features/editor/components/TextOptionModal/TextOptionModal.style.ts
- client/src/features/editor/components/TextOptionModal/TextOptionModal.tsx
- client/src/features/editor/components/block/Block.style.ts
- client/src/features/editor/components/block/Block.tsx
- client/src/features/editor/hooks/useBlockOption.ts
- client/src/features/editor/hooks/useMarkdownGrammer.ts
- client/src/features/editor/hooks/useTextOptions.ts
- client/src/features/editor/utils/domSyncUtils.ts
- client/src/stores/useSocketStore.ts
- client/src/styles/tokens/color.ts
- client/src/styles/typography.ts
- client/src/utils/caretUtils.ts
- pnpm-lock.yaml
- server/src/crdt/crdt.gateway.ts
- #180
- #20 
- #21 
- #22 
- #24 
- #27 
- #29 
- #56 
- #58 
- #59 
- #60 
- #61 
- #62 
- 
자세한 내용은 개발위키에 작성하겠습니다!
[리치 텍스트 구현하기](https://abrupt-feta-9a9.notion.site/6-45718cbb81d2432abf68c76c15dfa586?pvs=4)
- 동작만 확인했고, 최적화해야 할 부분이 존재합니다.
- 현재 "스타일 텍스트"<캐럿>"스타일 텍스트" 이런 경우에 중간에 공간이 하나 더 있는 것 처럼 동작하는 문제가 있습니다. 예를 들어 저 위치에서 텍스트를 삭제하려면 두번 백스페이스를 눌러야 한다거나 이동할때 화살표를 두번 움직여야 하는 등의 문제가 있습니다.
- 텍스트를 드래그하고 스타일을 적용했을 때 마지막 드래그한 위치에 캐럿이 위치하는게 아니라 이상한 곳으로 좀 튀는(?) 문제가 있습니다.
이부분은 추가로 계속 수정해보겠습니다!
https://github.com/user-attachments/assets/fe8c950b-0d65-406a-baf5-2b0b3411e102
https://github.com/user-attachments/assets/ecbbe80d-39eb-4609-ba35-99c461c4daf9
> Feature/#180 리치 텍스트 구현

- client/src/features/auth/AuthModal.style.ts
- client/src/features/auth/AuthModal.tsx
- client/src/styles/global.ts
- close #201
- 브라우저 자체에서 제공하는 배경색을 없애야했습니다.
- 검색해보니 `transition: "background-color 5000s ease-in-out 0s"` 속성을 활용하는걸 알게 되었고
- 이는 배경색 변경에 대한 트랜지션을 5000초(약 80분)으로 설정해, 자동완성 배경색을 설정하는걸 사실상 무효화하고 있습니다.
https://github.com/user-attachments/assets/8a01a2c4-62cb-43f7-a35d-614dd2333e31
> Feature/#201 자동완성 기본 ui 제거

- docker-compose.yml
- NginX 빌드 문제 수정
- FE와 BE 빌드 파일 권한 문제 해결하다가 NginX 권한도 바꿔버려서 NginX가 인증서에 접근을 못하고 있었습니다..ㅋㅋ
- NginX 빌드 권한을 이전으로 되돌렸습니다
> Hotfix/NginX 빌드 권한 수정

- docker-compose.yml
- 빌드 권한 문제로 계속 오류가 발생해서 이전으로 롤백합니다
- 일단은 롤백해서 배포 진행하고 나중에 다시 찾아본 뒤에 적용하겠습니다
> Hotfix/빌드 권한 설정 롤백

- client/src/features/editor/hooks/useMarkdownGrammer.ts
- client/src/features/editor/utils/domSyncUtils.ts
- #242 
- #include등 탐지되지 않아야 하는 글자도 탐지되는 문제가 있었습니다.
> Hotfix/#242 마크다운 탐지 로직 수정

- client/src/features/editor/components/TypeOptionModal/TypeOptionModal.tsx
- close #239
- esc를 누르거나, 옵션창 외부 클릭시 옵션창 사라지도록 구현
https://github.com/user-attachments/assets/86ed4b2e-fb6b-4584-9db0-ece54645a0bf
> Feature/#239 esc를 누르거나, 옵션창 외부 클릭시 옵션창 사라지도록 구현

- client/src/features/editor/utils/domSyncUtils.ts
- 죄송합니다...
- 죄송합니다...
- 죄송합니다...
- 죄송합니다...
> Hotfix: sanitize 롤백

- client/src/App.tsx
- client/src/features/editor/hooks/useEditorOperation.ts
- client/src/features/workSpace/components/OnboardingOverlay.tsx
- server/src/workspace/workspace.gateway.ts
- console.log 제거
- 디버깅용 console.log를 제거했습니다.
> Hotfix/console.log 제거

- client/src/features/editor/components/block/Block.tsx
- client/src/features/editor/hooks/useCopyAndPaste.ts
- 단축키로 텍스트 스타일 변경 구현
- cmd + b -> 볼드체 적용
- cmd + i -> 이탤릭체 적용
- cmd + shift + s -> 취소선 적용
- cmd + u -> 밑줄 적용
> Feature/#264 단축키로 텍스트 스타일 변경

- server/src/workspace/workspace.gateway.ts
- #276
https://github.com/user-attachments/assets/ea0e81a6-ae7c-47ca-826c-792f29e33f07
```js
currentPage.crdt.LinkedList.updateAllOrderedListIndices();
```
를 추가하였습니다.
- `delete/block`, `update/block`마다 서버의 리스트 상태도 동기화하도록 메소드를 추가하였습니다.
> Feature/#276 순서리스트 null나오는 현상

- client/src/features/editor/components/ColorOptionModal/BackgroundColorOptionModal.style.ts
- client/src/features/editor/components/ColorOptionModal/TextColorOptionModal.style.ts
- #275
- 그림자 효과를주고, white 토큰이 공유되도록 색을 설정했습니다.!
- backgroundColor역시 마찬가지입니다.
- EEEEEE -> FFFFFF 에서 그림자 추가했습니다.
https://abrupt-feta-9a9.notion.site/Panda-CSS-4d9305e445ef4ecf9d9105093d464514?pvs=4
> Feature/#275 흰색으로 바꾸고 그림자 효과를주어 흰색이 표시되게 변경

- client/src/features/editor/Editor.tsx
- #278
- backspace눌렀을때 캐럿 튀는 문제
> Feature/backspace눌렀을때 캐럿 튀는 문제

- client/src/features/editor/hooks/useEditorOperation.ts
- 사용하지 않는 position 변수 제거
- 사용하지 않는 position 변수 제거
> Feature/#303 사용하지 않는 position 변수 제거

- client/src/features/workSpace/hooks/usePagesManage.ts
#306
- client에서 page를 닫을때 socket 룸 pageid 에서 leave처리를 합니다.
- 변경 사항이 코드에 어떻게 반영되었는지, 특히 리뷰어가 주의해야 할 부분이 있다면 상세히 설명합니다.
> Feature/#306 leave/page 누락건 추가

- client/src/features/editor/hooks/useCopyAndPaste.ts
- ---(분할) 제외하고 마크다운 문법 붙여넣기 가능합니다.
- 대부분의 마크다운 문법 붙여넣기가 가능합니다.
> Hotfix/#308 마크다운 문법 붙여넣기 수정

- client/src/features/editor/hooks/useBlockOption.ts
- 블록 전환시 순서 리스트 유지
- 블록 전환시 순서 리스트 유지
> Hotfix/블록 전환시 순서 리스트 유지
