client/eslint.config.js
eslint.config.js
server/eslint.config.js
server/src/app.controller.spec.ts
server/src/app.controller.ts
server/src/app.module.ts
server/src/app.service.ts
server/src/main.ts
server/test/app.e2e-spec.ts

- #087
- ESLint가 dist 디렉토리를 검사하는 문제 수정
- ESLint의 ignores 명단이 모든 하위 디렉토리에 대해 정상적으로 적용되도록 수정
- 기존 ESLint 설정에서는 ignores의 명단이 정상적으로 적용되지 않는 문제가 있었음
```
ignores: [
'node_modules/',
'dist/',
'build/',
'coverage/',
'*.config.js',
'src/**/*.test.js',
'public/*',
'server/dist/'
],
```
- 디렉토리 경로 문제로, ignores 명단이 루트 디렉토리에서만 작동했음
- ignores 명단이 모든 하위 디렉토리에서 정상적으로 제외되도록 수정
- 이에 따라 `server/dist/`는 중복되므로 제거
```
ignores: [
"**/node_modules/",
"**/dist/",
"**/build/",
"**/coverage/",
"**/*.config.js",
"**/src/**/*.test.js",
"**/public/*",
],
```
- dist는 모든 하위 디렉토리에 대해서 일괄적으로 ignore가 되는 것이 맞는데, ignores 명단의 다른 디렉토리도 하위 디렉토리에 대해서 일괄적으로 적용되야 하는 게 맞나요? 루트 디렉토리에서만 ignore돼야 한다면 이 점은 수정하겠습니다.

Feature/#087 ESLint가 dist를 검사하는 문제 수정

---

client/eslint.config.js
eslint.config.js
package.json
server/eslint.config.js
server/jest.config.ts
server/src/app.controller.spec.ts
server/src/app.controller.ts
server/src/app.module.ts
server/src/app.service.ts
server/src/main.ts
server/test/app.e2e-spec.ts

- #086
- Jest 환경 설정 파일 추가
- 이전까지 NestJS에서 테스트를 수행했을 때 다음 문제가 발생해서 환경 설정 파일을 추가했습니다.
- TypeScript 문법 지원 안됨
- ECMAScript 모듈 지원 안됨
- [참고 링크](https://abrupt-feta-9a9.notion.site/NestJS-Jest-ec242227d56b47aea0dba07a81c48aab)

Feature/#086 Jest 환경 설정 파일 추가

---

.github/workflows/auto_merge_approved_pr.yml
.github/workflows/deploy.yml
.github/workflows/lint_and_test.yml

- #085
- PR을 올릴 때마다 자동으로 lint와 테스트를 수행하는 workflow 추가
- 2명 이상이 approve한 PR을 자동으로 merge하는 workflow 추가
- PR 자동 merge workflow의 경우 재도님이 공유하신 글을 참고해서 작성했습니다.
- [참고자료](https://harsh-flier-3c0.notion.site/134b1b2b6491805a9ecec64c898bfddd)

Feature/#085 Github Actions workflow 추가

---

.github/workflows/auto_merge_approved_pr.yml

- #085
- auto_merge_approved_pr.yml에서 발생하는 오류 수정
```
Run actions/github-script@v6
ReferenceError: steps is not defined
at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15143:16), <anonymous>:3:23)
at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15144:12)
at main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15236:26)
at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:15217:1
at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:15268:3
at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15271:12)
at Module._compile (node:internal/modules/cjs/loader:1358:14)
at Module._extensions..js …
```

Feature/#085 auto_merge_approved_pr.yml 오류 수정

---

.gitignore
@noctaCrdt/package.json
@noctaCrdt/tsconfig.json
client/package.json
client/tsconfig.json
client/vite.config.ts
package.json
pnpm-lock.yaml
pnpm-workspace.yaml
server/nest-cli.json
server/package.json
server/tsconfig.json
server/webpack.config.js

- #98 
- CRDT 라이브러리 폴더 생성
- pnpm 라이브러리화 후 client, server에 의존성 주입
- package.json에 build 관련 script명령어 추가
- client, server의 tsconfig.json 설정 변경
- clinet는 vite기반의 ESM으로 동작하고, server는 nestJS CommonJS으로 동작합니다. 
- 두 환경에서 다 동작하도록 dist/에 생성되는 js를 import하도록 설정하였습니다.
- server의 경우 nestJS기본 cli환경설정에서는 server 외부의 폴더를 접근하지 못합니다.
- 그래서 webpack으로 빌드하여 dist를 추적하도록 설정하였습니다.
- https://abrupt-feta-9a9.notion.site/4-CRDT-8bf2d66eb6624ebf8984c4e78d847176?pvs=4
- build시 전부 Done 확인

Feature/#098 nocta crdt 라이브러리 client, server가 접근 가능하도록 환경 구축

---

.gitignore
@noctaCrdt/Crdt.ts
@noctaCrdt/Interfaces.ts
@noctaCrdt/LinkedList.ts
@noctaCrdt/Node.ts
@noctaCrdt/package.json
@noctaCrdt/tsconfig.json
client/package.json
client/tsconfig.json
client/vite.config.ts
package.json
pnpm-lock.yaml
pnpm-workspace.yaml
server/nest-cli.json
server/package.json
server/tsconfig.json
server/webpack.config.js

- #19 
- #25 
- #31 
- CRDT 클래스 선언
- LinkedList 클래스 선언
- Node 클래스 선언
- Interface 파일 생성
기본 4개로 구성 되어있습니다.
1. 로컬 삽입 : 삽입 연산을 반영하고 서버에 삽입 연산을 송신
2. 로컬 삭제 : 삭제 연산을 반영하고 서버에 삭제 연산을 송신
3. 원격 삽입 : 서버로부터 삽입 연산을 받음
4. 원격 삭제 : 서버로부터 삭제 연산을 받음
위 동작을 위한 내부 메소드들이 선언되어 있습니다.
연결, 재연결을 할때 client <-> server가 CRDT 정보를 주고받기 위해서 CRDT의 직렬화된 정보를 주고받기 위해
serialized 정보역시 메소드로 선언 되어 있습니다.
client에서는 server로부터 CRDT를 받아 역직렬화를 하고 각 동작을 server와 송/수신 해야 합니다.
server는 수신받은 연산을 반영한 CRDT 정보를 mongoDB에 주기적으로 업데이트 해줘야합니다.
- https://abrupt-feta-9a9.notion.site/3-FE-BE-CRDT-8da3ae01ddf349829ea4dc9639ba2f94?pvs=4
- 아직 클래스선언과 내부동작정도만 코드에 반영이 되었습니다. 추후 client와 server에서 테스트할 수 있도록 동작을 추가할 예정입니다.

Feature/#019 crdt 동시 편집 구현

---

client/package.json
client/src/components/sidebar/Sidebar.animation.ts
client/src/components/sidebar/Sidebar.style.ts
client/src/components/sidebar/Sidebar.tsx
client/src/constants/size.ts
client/src/features/page/hooks/usePage.ts
client/src/stores/useSidebarStore.ts
pnpm-lock.yaml

- 사이드바 반응형 구현
- constants의 상수만 바꾸면 사이드바 크기 수정가능합니다.
- sidebar 열림/닫힘의 경우, zustand로 관리하는편이 좋다 생각했습니다 (여러곳에서 접근해야함)
- zustand 설치 및 적용
- 현훈님이 정리하신 부분이랑 해당 [블로그](https://tkdodo.eu/blog/working-with-zustand) 참고해서 구현했습니다.
- 자세한 거는 따로 위키에 작성하겠습니다!
https://github.com/user-attachments/assets/ef3efea7-1eb5-4d6a-a5f3-0d8ac367455f

Feature/#104 탭 브라우징 반응형 구현

---

.github/workflows/deploy.yml
.github/workflows/lint_and_test.yml
.gitignore
docker-compose.debug.yml
docker-compose.yml
pnpm-lock.yaml
server/jest-mongodb-config.ts
server/jest.config.ts
server/package.json
server/src/app.module.spec.ts
server/src/app.module.ts

- #097
- Github Secrets 환경 변수 이름 변경
- 테스트 환경에서 테스트용 MongoDB 서버를 열 수 있도록 코드 수정
- 모든 브랜치에서 Push할 때마다 lint와 test를 수행하도록 Github Actions 변경
- 환경 변수 수정하는 데 있어 기타 자잘한 부분도 같이 변경했습니다.
- 개발 환경에서 NestJS 애플리케이션을 실행할 때에는 로컬에 MongoDB가 27017 포트로 실행되고 있어야 합니다.

Feature/#097 MongoDB 테스트 환경 구축

---

@noctaCrdt/Crdt.ts
@noctaCrdt/Interfaces.ts
@noctaCrdt/LinkedList.ts
@noctaCrdt/Page.ts
@noctaCrdt/WorkSpace.ts

- CRDT 라이브러리 내 WorkSpace, Page 클래스 생성
- LinkedList, CRDT 내부 객체 및 메소드 이름 변경
- DB스키마에 맞게 필요한 클래스들을 생성하였습니다.

Feature/#117 crdt 라이브러리 개선

---

@noctaCrdt/Crdt.ts
@noctaCrdt/Interfaces.ts
@noctaCrdt/LinkedList.ts
@noctaCrdt/Node.ts
@noctaCrdt/NodeId.ts
@noctaCrdt/Page.ts
@noctaCrdt/WorkSpace.ts

- CRDT라이브러리를 DB스키마에 맞게 활용할 수 있도록 개선합니다.
- CRDT -> EditorCRDT, BlockCRDT 클래스 상속하여 생성
- LinkedList -> BlockLinkedList, TextLinkedList 클래스 상속하여 생성
- Node, NodeID 등 Block과 Char에 따라 Id 클래스 생성함

Feature/#121 crdt 라이브러리 db스키마로 개선

---

.github/workflows/deploy.yml
.github/workflows/lint_and_test.yml
docker-compose.yml

- #136
- 배포 환경에서 JWT_SECRET 환경변수를 읽지 못하는 문제 수정
- NginX Docker 이미지에 Certbot 인증 파일에 대한 볼륨 마운트 추가
- 

Feature/#136 NginX HTTPS 관련 버그 수정

---

@noctaCrdt/Crdt.ts
@noctaCrdt/Interfaces.ts
client/src/apis/useSocket.ts
client/src/features/editor/Editor.tsx
client/src/features/editor/components/block/Block.tsx
client/src/features/editor/hooks/useMarkdownGrammer.ts
server/src/crdt/crdt.gateway.ts
server/src/crdt/crdt.service.ts

https://github.com/user-attachments/assets/4ff021fe-451c-4571-9821-35487ff5a4c3
- client와 server가 CRDT로 통신합니다. 
- client에서 사용하는 api
```js
socketRef.current.on("assignId",
socketRef.current.on("document", 
socketRef.current.on("connect",
socketRef.current.on("disconnect", 
socketRef.current.on("error",
socketRef.current?.emit("insert/block", operation);
socketRef.current?.emit("insert/char", operation);
socketRef.current?.emit("delete/block", operation);
socketRef.current?.emit("delete/char", operation);
socketRef.current?.emit("cursor", position);
// server의 경우
client.broadcast.emit("userLeft", { clientId: clientInfo.clientId });
//유저 떠남 정도가 있음.
```
- CRDT라이브러리를 통해 클라이언트와 서버가 socket.io로 통신합니다.
- useSocket() 훅을 만들어서 통신을 관리하고 이벤트에 따라 동작합니다.
- 현재는 Page 컴포넌트 한곳에서 동작합니다. 
.env에서 아래와 같이 입력했습니다. …

Feature/#109 crdt 클라이언트 서버 연동

---

@noctaCrdt/Crdt.ts
@noctaCrdt/Interfaces.ts
client/src/features/editor/Editor.tsx
client/src/features/editor/hooks/useBlockDragAndDrop.ts
client/src/stores/useSocketStore.ts
server/src/crdt/crdt.gateway.ts

- 블록 드래그 앤 드랍 서버 반영
- CRDT 라이브러리 remoteReorderOperation 타입 수정
- useBlockDragAndDrop 커스텀 훅에서 DragEnd시 서버로 연산 operation 전송
- useSocketStore에 reorder/block socket 이벤트 등록
- crdt.gateway.ts에 reorder/block 핸들러 등록
- 기존 로직에 맞게 드래그 앤 드롭도 socket으로 operation 전송해서 다른 클라이언트에 이벤트를 발생시킵니다.
https://github.com/user-attachments/assets/bffb78cf-e196-4b8e-81d6-6241e3107b4b

Feature/#168 블록 드래그앤드랍 서버 반영

---

client/src/features/editor/components/MenuBlock/MenuBlock.style.ts
client/src/features/editor/components/MenuBlock/MenuBlock.tsx
client/src/features/editor/components/block/Block.style.ts

- #042
https://github.com/user-attachments/assets/1ebd6706-d4cb-4a5a-90e9-d06210423cfc
- 블록에 마우스가 hover됐을때 해당블록의 menuBlock이 보입니다.
- menu_block 이란 클래스와, option_modal_open 클래스를 추가하여 block.style.ts에 반영했습니다.

Feature/#042 블록에 마우스를 호버하면 한 쪽 끝에 옵션 버튼 구현

---

client/src/features/editor/Editor.tsx
client/src/features/editor/components/block/Block.tsx
client/src/features/editor/hooks/useMarkdownGrammer.ts

- 한글 crdt 연동되도록 구현
- [해당 PR](https://github.com/boostcampwm-2024/web33-Nocta/pull/170)부터 리뷰 부탁드립니다!
- composing 처리로 해결했습니다
- 디버깅과정은 [해당 링크](https://abrupt-feta-9a9.notion.site/1469ff1b21c380e48b25e41283e88ef5?pvs=4)에 정리했습니다
https://github.com/user-attachments/assets/6bfb6d63-82ab-495e-bc30-3016092545d0

Feature/#171 한글 crdt 연동되도록 구현

---

client/src/features/page/Page.style.ts
client/src/features/page/Page.tsx
client/src/features/page/hooks/usePage.ts

- close #178
- 페이지 리사이징 기능 확장
- 8방향에 대해 모두 리사이징이 가능하도록 구현했습니다.
- 사이즈를 조절할때마다 애니메이션이 돌면 안되기 때문에, page에 있는 framer motion 애니메이션을 뺐습니다. 추후 page 컴포넌트가 생성되는 시점에만 애니메이션을 주는걸 더 찾아보겠습니다!
- 계산 과정은 [개발위키](https://abrupt-feta-9a9.notion.site/1479ff1b21c380038bd1fd6ba430fef2?pvs=4)에 정리했습니다!
https://github.com/user-attachments/assets/5b018893-3dac-41fb-a4cc-a07fae23e115

Feature/#178 페이지 리사이징 기능 확장

---

@noctaCrdt/Interfaces.ts
@noctaCrdt/WorkSpace.ts
client/src/components/sidebar/PageItem.style.ts
client/src/components/sidebar/PageItem.tsx
client/src/components/sidebar/Sidebar.style.ts
client/src/components/sidebar/Sidebar.tsx
client/src/features/editor/Editor.style.ts
client/src/features/workSpace/hooks/usePagesManage.ts
client/src/stores/useSocketStore.ts
server/src/crdt/crdt.gateway.ts

https://github.com/user-attachments/assets/9b567571-d119-4857-abb4-17a21b43d068
- 페이지 아이템에 마우스를 hover시, close 아이콘을 표시합니다.
- close 아이콘을 클릭 시, 페이지를 삭제합니다.
- deleteOperation 추가
- delete/page 추가
- create/page 처럼 delete/page를 추가하였습니다.
- 최소 1개 페이지가 남기게 변경하였습니다.
- 추후 broadcast 하는부분이 전부 to(userId) 로 바뀔예정인데, 일단 broadcast로 작업하겠습니다.
- 그리고 workspace연동 PR에서 이 PR을 pull 해서 변경사항을 반영하여 다시 PR올리겠습니다.!

Feature/#184 페이지 삭제 구현

---

@noctaCrdt/Crdt.ts
@noctaCrdt/Interfaces.ts
@noctaCrdt/LinkedList.ts
@noctaCrdt/Node.ts
client/package.json
client/src/constants/color.ts
client/src/constants/option.ts
client/src/features/editor/Editor.tsx
client/src/features/editor/components/ColorOptionModal/BackgroundColorOptionModal.style.ts
client/src/features/editor/components/ColorOptionModal/BackgroundColorOptionModal.tsx
client/src/features/editor/components/ColorOptionModal/TextColorOptionModal.style.ts
client/src/features/editor/components/ColorOptionModal/TextColorOptionModal.tsx
client/src/features/editor/components/TextOptionModal/TextOptionModal.style.ts
client/src/features/editor/components/TextOptionModal/TextOptionModal.tsx
client/src/features/editor/components/block/Block.style.ts
client/src/features/editor/components/block/Block.tsx
client/src/features/editor/hooks/useBlockOption.ts
client/src/features/editor/hooks/useMarkdownGrammer.ts
client/src/features/editor/hooks/useTextOptions.ts
client/src/features/editor/utils/domSyncUtils.ts
client/src/stores/useSocketStore.ts
client/src/styles/tokens/color.ts
client/src/styles/typography.ts
client/src/utils/caretUtils.ts
pnpm-lock.yaml
server/src/crdt/crdt.gateway.ts

- #53 
복사, 붙여넣기, 한번에 삭제 모두 브라우저 기본 이벤트를 막습니다.
- 텍스트 복사: 드래그 해서 선택된 텍스트의 노드를 찾습니다. 선택된 노드들의 스타일 정보가 있으면 스타일 정보를 포함한 메타데이터를 클립보드에 저장합니다(text/plain이 아닌 객체 형식)
- 텍스트 붙여넣기
- 일반 텍스트일 경우: text/plain에 저장되어 있는 텍스트 정보를 한글자씩 삽입 연산을 서버로 전송합니다.
- 스타일 텍스트일 경우: 클립보드에 저장한 객체를 가지고 와서 각 노드별로 value와 스타일을 적용한 텍스트 삽입 연산을 서버에 전송합니다.
- 텍스트 한번에 삭제: 드래그 해서 선택된 텍스트의 노드를 찾습니다. 선택된 노드들을 하나씩 삭제 연산처리해서 서버로 전송합니다.
- 현재 색상 관련된 데이터가 클라이언트간에 통신이 안되고 있는 것 같습니다. 이 부분은 확인해보고 수정하겠습니다.
- 붙여넣기 할때, 특정 조건에서 캐럿이 이전 위치에 계속 있는 문제가 있는 것 같은데 어떤 조건에서 일어나는 문제인지는 아직 확인하지 못했습니다.
혹시 문제되는 부분 발견하시면 피드백 부탁드립니다!
https://github.com/user-attachments/assets/d75ac56c-4560-4aae-b1d6-787a2489d1c5

Feature/#053 블럭내 복사 붙여넣기 구현

---

client/src/features/editor/Editor.tsx
client/src/features/page/Page.tsx
client/src/features/workSpace/WorkSpace.tsx

- close #193
- 한글 캐럿 계속 업데이트 되는 문제 수정
- 변경 사항이 코드에 어떻게 반영되었는지, 특히 리뷰어가 주의해야 할 부분이 있다면 상세히 설명합니다.

Feature/#193 한글 캐럿 계속 업데이트 되는 문제 수정

---

client/src/features/editor/Editor.tsx
client/src/features/editor/components/TextOptionModal/TextOptionModal.tsx

- #206 
- 텍스트 모달 UX 개선
- 텍스트를 드래그하고 있는 상태에서 모달창 내부를 클릭할때는 포커스 사라지지 않음
- 색상과 배경 버튼은 hover할때만 서브 모달이 나오고, 두 버튼을 클릭해도 동작하지 않도록 수정
- 텍스트 입력시, 이전 텍스트에 스타일이 적용되어 있으면 동일한 스타일로 삽입
- 평소에는 잘 작동하는데, 맥 영상 녹화를 틀면 버튼에 마우스를 올려도 포인터로 안바뀌는 문제가 있습니다. 코드 문제는 아닌 것 같은데, 이유를 잘 모르겠습니다...
https://github.com/user-attachments/assets/4d2b35f1-041c-4c2e-b99d-9eed30bdcc69

Feature/#206 이전 텍스트 스타일 연속으로 적용

---

client/src/constants/option.ts
client/src/features/editor/components/OptionModal/OptionModal.style.ts
client/src/features/editor/components/TypeOptionModal/TypeOptionModal.tsx
client/src/features/editor/components/block/Block.tsx

- `/` 를 입력하여 블록 생성 목록 구현
- `/` 은 마크다운과 다르게 입력하자마자 `/`를 확인하고, 옵션 모달창을 띄워줘야하기에 input 핸들러에서 동작합니다.
- 또한 p태그 뿐만 아니라 h1, h2에서도 `/` 입력이 오면 옵션 모달창을 띄워주었습니다.
- 키보드 이동 (위/아래)에 따라 옵션을 선택가능하고, 엔터를 치면 저장됩니다
- 마우스 이동으로도 선택가능하며, 옵션 모달창은 esc를 누를경우/리스트 중 하나를 선택했을 경우 닫아줍니다.
https://github.com/user-attachments/assets/f888bba7-0220-47ae-b6d9-e8dbb89fca40

Feature/#39 슬래시를 입력하여 블록 생성 목록 구현

---

client/src/features/editor/hooks/useBlockOption.ts

- close #212
- 하위 요소까지 복제 삭제 기능 구현
- 현재 올려져있는 PR을 다 풀받은 상태에서 작업했습니다! 나중에 머지되면 푸시하겠습니다
- 삭제의 경우, 하위 요소들부터 먼저 삭제되도록 구현했습니다! 그편이 ux측면에서 낫다고 생각했습니다
https://github.com/user-attachments/assets/d3526f37-6e96-4c8b-bdda-9b18850dc4d9

Feature/#198 하위 요소까지 복제 삭제 기능 구현

---

@noctaCrdt/Crdt.ts
@noctaCrdt/LinkedList.ts
@noctaCrdt/Node.ts
client/src/features/editor/components/IconBlock/IconBlock.tsx
client/src/features/editor/components/block/Block.tsx
client/src/features/editor/hooks/useBlockOption.ts
client/src/features/editor/hooks/useMarkdownGrammer.ts

- #11 
- 순서있는 리스트 생성시 순서를 반영해서 iconBlock의 숫자를 갱신합니다.
- 리스트 생성시, 이전 인덱스보다 1 증가시켜서 생성
- 리스트 중간에서 기본 블록으로 변경할 때, 두 리스트로 분할해서 각각 1부터 시작
- indent 증가시 1부터 시작
- indent 감소시 기존 순서에 맞게 변경
- 두개의 순서 리스트 병합시, 먼저 있는 리스트에 합쳐서 숫자 시작
CRDT의 BlockLinkedList에 `updateAllOrderedListIndices` 메서드를 구현해서 현재 연산이 순서 리스트일 경우, 모든 블록을 순회하며 리스트의 index를 갱신합니다. 기존에는 각 케이스별로 코드를 작성했는데 이렇게 하다보니까 에러도 많이 발생하고 코드의 길이가 늘어나서 LinkedList 메서드로 분리해서 사용하는 식으로 구현했습니다.
블록을 모두 순회하는 로직이다보니 자주 실행하면 성능에 영향을 줄 수 있을것 같아 순서리스트 연산일때만 실행시키도록 분기 처리했습니다.
- 혹시 엣지케이스나 에러케이스 등 문제가 발생하는 부분이 있으면 피드백 부탁드립니다!
https://github.com/user-attachments/assets/7a9c6ab4-d64f-4756-a96f-37a5a1188f3a

Feature/#011 순서있는 리스트 숫자 구현

---

client/src/features/editor/components/block/Block.style.ts
client/src/features/editor/utils/domSyncUtils.ts

- #220
- `sanitizeText` 함수로 특수문자를 html 엔티티로 변경하는 부분에서 문제가 발생했습니다.
- 블록의 style에 `whiteSpace: "pre-wrap"` 속성을 추가하여 공백과 줄바꿈 문자가 유지되도록 수정했습니다.
https://github.com/user-attachments/assets/cfec631a-a4be-4a27-977d-0a68b52259ba

Hotfix/#220 특수문자 있는 경우에도 텍스트 드래그 되도록 수정

---

client/src/features/editor/components/block/Block.style.ts
client/src/features/editor/components/block/Block.tsx
client/src/features/editor/hooks/useBlockOperation.ts
client/src/features/editor/hooks/useBlockOption.ts
client/src/features/editor/hooks/useCopyAndPaste.ts
client/src/features/editor/hooks/useMarkdownGrammer.ts
client/src/features/editor/utils/domSyncUtils.ts

- #222 
[마크다운 트러블슈팅](https://abrupt-feta-9a9.notion.site/3-03f49cec59bb43c992dad1189110c279?pvs=4)
- 혹시 아직 에러나는 부분 있으면 말씀해주세요!
https://github.com/user-attachments/assets/219e544f-33d9-482d-823b-d6ffa4b4d7fe
https://github.com/user-attachments/assets/e19b48e7-13b5-4c0c-a36c-2d3a786387a7

Hotfix/#222 드래그하고 입력할때 텍스트 안지워지는 문제 해결

---

@noctaCrdt/Interfaces.ts
client/src/components/Toast/Toast.style.ts
client/src/components/Toast/Toast.tsx
client/src/components/Toast/ToastContainer.style.ts
client/src/components/Toast/ToastContainer.tsx
client/src/components/sidebar/Sidebar.tsx
client/src/components/sidebar/components/pageItem/PageItem.tsx
client/src/features/workSpace/WorkSpace.tsx
client/src/features/workSpace/hooks/usePagesManage.ts
client/src/stores/useToastStore.ts
client/src/types/toast.ts
server/src/crdt/crdt.gateway.ts

- #234 
https://github.com/user-attachments/assets/e57ffdef-1a11-407c-8606-99ab7e2c1fb0
- 페이지가 삭제될때 화면 우측 하단에 toast 토글창을 생성합니다.
- toast 컴포넌트 생성, toast 컨테이너 컴포넌트 생성
- useToastStore로 선언하여 원하는 메세지를 addToast로 표시 가능.
- delete/page 할때 pageTitle도 보내게 변경

Feature/#234 페이지 삭제시, 삭제 토글창 알림

---

client/src/components/sidebar/components/pageItem/PageItem.tsx
client/src/features/editor/Editor.tsx

- #231
- #233
- 다른 사용자가 페이지 제목을 바꾸면 로컬의 페이지 제목도 바로 바뀌도록 수정했습니다.
- 새로운 페이지일때는 빈칸이 들어가도록 수정했습니다.
https://github.com/user-attachments/assets/00d741cf-f3ab-41e8-bd02-0711436b805e
- 사이드바 아이콘 동기화 안되는 버그 수정
https://github.com/user-attachments/assets/63a3acfd-2001-468e-8244-a7d5f1a68ec4
- useEffect로 의존성 주입하였습니다.

Feature/#231_remote페이지_제목_반영_안되는_버그 및 아이콘 반영 버그 수정

---

client/src/features/editor/hooks/useMarkdownGrammer.ts

- close #236
- 각 이벤트(tab, 위아래, 좌우)에 대해 isComposing일 경우 return 해줘서 이벤트를 막았습니다.
https://github.com/user-attachments/assets/5e78f797-82b0-45d3-93b2-18118121c984

Feature/#236 문제상황에 대해 isComposing 일 경우 이벤트 막도록

---

client/src/components/bottomNavigator/BottomNavigator.tsx
client/src/components/button/IconButton.tsx
client/src/components/button/textButton.tsx
client/src/components/sidebar/Sidebar.tsx
client/src/components/sidebar/components/menuButton/MenuButton.tsx
client/src/features/auth/AuthButton.tsx
client/src/features/workSpace/WorkSpace.tsx
client/src/features/workSpace/components/OnboardingOverlay.style.ts
client/src/features/workSpace/components/OnboardingOverlay.tsx

https://github.com/user-attachments/assets/3642cabb-b466-4530-b26c-6f67edd466b8
- 온보딩 오버레이를 추가했습니다.
- 온보딩오버레이가 추적하기 위해 sideBar나 페이지 추가버튼, loginButton 에 `data-onBoarding` props를 추가했습니다.

Feature/#253 온보딩 오버레이 추가

---

client/src/components/bottomNavigator/BottomNavigator.tsx
client/src/components/button/IconButton.style.ts
client/src/components/button/textButton.style.ts
client/src/components/sidebar/Sidebar.style.ts
client/src/features/auth/AuthButton.style.ts
client/src/features/auth/AuthButton.tsx
client/src/features/page/Page.tsx
client/src/features/page/components/PageControlButton/PageControlButton.style.ts
client/src/features/page/components/PageControlButton/PageControlButton.tsx
client/src/features/page/hooks/usePage.ts
client/src/features/workSpace/WorkSpace.style.ts
client/src/features/workSpace/WorkSpace.tsx
client/src/features/workSpace/hooks/usePagesManage.ts
client/src/styles/global.ts

- close #240
- 페이지 반응형 구현 및 피드백 반영
- 멘토링 시간때 멘토님께서 말씀하셨던 사이드바 여닫을때마다 하얀 박스가 생기는 문제 해결
- 페이지 최대화시, 최소화버튼은 비활성화되며 최대화버튼을 다시 눌러야 원래 크기,위치로 돌아가도록
- 화면 크기에 따라 페이지 크기도 반응형으로 수정. -> 최대화상태에서는 계속 최대화되도록
- 보여줄 페이지가 하나도 없을 경우, bottom navigator는 안보이도록
- 페이지가 보여질때, 오버플로우되지 않도록 수정
- 페이지 최대화시, 최소화버튼은 비활성화되며 최대화버튼을 다시 눌러야 원래 크기,위치로 돌아가도록
https://github.com/user-attachments/assets/d6de571d-d8bf-49e5-94f1-0eb4575c969b
- 페이지가 보여질때, 오버플로우되지 않도록 수정 (오른쪽 하단에 계속 생기도록)
https://github.com/user-attachments/assets/e86e43ea-8d74-4060-9acd-daf74cb772de
- 화면 크기에 따라 페이지 크기도 반응형으로 수정. -> 최대화상태에서는 계속 최대화되도록
https://github.com/user-attachments/assets/1d269bef-0ad4-4aba-a2cc-f131ff376737

Feature/#240 페이지 반응형 구현

---

client/src/features/editor/Editor.tsx
client/src/features/editor/hooks/useBlockOperation.ts

- 블록에 한글 첫입력시 서버에서 에러가 나는 문제
- composingCaret.current가 number로 관리가 되는데 분기 처리를 할 때 0인 경우 falsy한 값으로 처리가 되어 !composingCaret.current가 true가 되는 문제가 있었습니다

Hotfix/#252 블록에 한글 첫입력시 캐럿 튀는문제

---

client/src/assets/icons/pencil.svg
client/src/components/modal/RenameModal.style.ts
client/src/components/modal/RenameModal.tsx
client/src/components/sidebar/components/menuButton/MenuButton.style.ts
client/src/components/sidebar/components/menuButton/MenuButton.tsx
client/src/components/sidebar/components/menuButton/components/components/WorkspaceSelectItem.style.tsx
client/src/components/sidebar/components/menuButton/components/components/WorkspaceSelectItem.tsx
client/src/features/workSpace/components/OnboardingOverlay.style.ts
client/src/features/workSpace/components/OnboardingOverlay.tsx
client/src/stores/useSocketStore.ts
client/src/stores/useWorkspaceStore.ts
server/src/workspace/workspace.gateway.ts
server/src/workspace/workspace.service.ts

https://github.com/user-attachments/assets/6a3c82fa-c84a-425e-9246-b166a21fb7cd
- 이름변경 모달
- 이름변경용 연필모양 버튼 추가
https://github.com/user-attachments/assets/efe3953f-348b-4a96-a320-46fe67f83ef9
- api를 추가했습니다. `workspace/user/join` , `workspace/user/leave` 로 판단합니다.
- api를 추가했습니다. `workspace/rename`을 수신하고 `workspace/list`를 보내서 갱신합니다.

Feature/#269 workspace 관련 완성도 개선

---

@noctaCrdt/Interfaces.ts
@noctaCrdt/Node.ts
client/src/features/editor/Editor.tsx
client/src/features/editor/components/IconBlock/IconBlock.style.ts
client/src/features/editor/components/IconBlock/IconBlock.tsx
client/src/features/editor/components/block/Block.tsx
client/src/features/editor/hooks/useBlockOperation.ts
client/src/features/editor/hooks/useEditorOperation.ts
client/src/stores/useSocketStore.ts
server/src/workspace/workspace.gateway.ts

- 체크박스 기능 추가
-  체크박스 기능 추가
https://github.com/user-attachments/assets/eae11c12-9710-4703-a77d-a6c9ecd5791d

Feature/#270 체크박스 기능 추가

---

client/src/features/editor/Editor.tsx

- 윈도우 remote 이벤트 수정
- request 애니메이션 제거
- 윈도우에서 한번에 end 이벤트에서 모든 텍스트기 한번에 remote 되도록 수정
- request 애니메이션 제거하여 caret 달라지는 문제 수정
- [개발위키](https://abrupt-feta-9a9.notion.site/1519ff1b21c380e1bd03e999ceb65282?pvs=4)에 정리중입니다!

Hotfix/#278 캐럿이 계속 튀는 문제

---

client/src/apis/auth.ts
client/src/components/inputField/InputField.style.ts
client/src/components/inputField/InputField.tsx
client/src/features/auth/AuthButton.tsx
client/src/features/auth/AuthModal.style.ts
client/src/features/auth/AuthModal.tsx

https://github.com/user-attachments/assets/50a538ac-b240-47cf-ba6d-0fc6962b517d
- 로그인 모달달창의 유효성 검사를 진행합니다.
- isError에 따라 에러메세지를 보여줍니다.

Feature/#279 회원가입 유효성 검사 구현

---

@noctaCrdt/Crdt.ts
client/src/features/editor/hooks/useBlockOperation.ts

- #285 
- data 의 속성에 color, background가 있는게 아니고 data.node에 color, background속성이 존재하는데 data.color, data.background 속성으로 접근하는 문제가 있었습니다.

Hotfix/#286 스타일 적용된 텍스트 이어서 작성할 때 서버 반영 안되는 문제 해결

---

client/src/features/editor/components/block/Block.tsx
client/src/features/editor/utils/domSyncUtils.ts

- 스타일 적용된 태그에 스페이스만 남아있을 때 에러나는 문제
- 제 자신과의 싸움이었습니다...
- 기존 로직에서 input 실행되기 전에 빈 span태그를 삭제하는 로직이 있어서 TreeWalker에서 해당 태그를 탐지하지 못하는 문제였습니다.

Hotfix/#288 스타일 적용된 태그에 스페이스만 남아있을 때 에러나는 문제

---

client/src/features/editor/utils/domSyncUtils.ts
client/src/stores/useSocketStore.ts

- 다른 블록에서 캐럿 튀는 문제, 배치 처리 다시 추가
- 다른 블록에서 캐럿 튀는 문제, 배치 처리 다시 추가

Hotfix/#288 다른 블록에서 캐럿 튀는 문제, 배치 처리 다시 추가

---

@noctaCrdt/Interfaces.ts
client/src/constants/option.ts
client/src/features/editor/components/block/Block.animation.ts

- #282
- 인터랙티브 컴포넌트 추가
- 인터랙티브 컴포넌트 추가 (그라데이션, 페이드인, 슬라이드인, 펄스, 바운스)
https://github.com/user-attachments/assets/8e0a20f7-6158-4518-b567-d54ac9c3d087

Feature/#282 인터랙티브 컴포넌트 추가

---

server/src/auth/auth.controller.ts
server/src/auth/auth.service.ts
server/src/auth/guards/jwt-auth.guard.ts
server/src/auth/schemas/user.schema.ts
server/src/auth/test/auth.controller.spec.ts
server/src/auth/test/auth.service.spec.ts

- #293
- Access Token이 stateless하게 관리될 수 있도록 tokenVersion을 제거했습니다.
- 변경 사항이 코드에 어떻게 반영되었는지, 특히 리뷰어가 주의해야 할 부분이 있다면 상세히 설명합니다.

Feature/#293 Access Token 인증 과정에서 tokenVersion 제거

---

server/src/workspace/schemas/workspace.schema.ts
server/src/workspace/workspace.gateway.ts
server/src/workspace/workspace.service.ts

- 서버 <-> 몽고DB가 저장되지 않는 현상을 수정했습니다.
- 클라이언트 <-> 서버와 실시간 사용자수, workspace정보를 주고받으면서 DB스키마가 바뀌었습니다.
- 이에따라 mongoDB에 저장되는 데이터 타입도 수정하였고, invite등의 정보를 수정하였습니다.
- DB스키마에서 AuthUser(권한)를 workspace단에서는 {}객체`(userId: "editor")`로, user에서는 접근 가능한 workspace정보로 배열로 관리했습니다. [ 0:(workspaceId)]

Feature/#295 db에 문서가 저장되지 않는 문제 수정

---

client/src/features/editor/hooks/useCopyAndPaste.ts

- #299 
현재 붙여넣기 지원되는 문법은 다음과 같습니다
- 모든 제목 태그
- 순서 리스트
- 순서 없는 리스트

Hotfix/#299 붙여넣기 할 때 순서 리스트 유지되도록 수정

---

client/src/App.tsx
client/src/components/backgroundImage/BackgroundImage.tsx
client/src/styles/global.ts

- 기존에는 css @support로 지원하게 했는데, avif를 지원함에도 webp를 받아왔습니다
- 이에 picture 태그를 이용해 avif를 우선으로 받아오도록 수정했습니다.
- 변경 사항이 코드에 어떻게 반영되었는지, 특히 리뷰어가 주의해야 할 부분이 있다면 상세히 설명합니다.

Feature/#267 이미지 최적화

---

client/src/components/sidebar/components/menuButton/MenuButton.tsx
client/src/features/workSpace/hooks/usePagesManage.ts

- close #255
- close #298
- 페이지 선택할때 화면 벗어나가지 않도록 수정
- dom nesting 에러 해결
- 페이지 선택할때 화면 벗어나가지 않도록 수정
- dom nesting은 button 태그안에 button이 있었기 때문 -> div로 바꾸고 접근성을 생각해 role을 button으로 수정해줬습니다
https://github.com/user-attachments/assets/ebb3af91-1b63-4d4b-8054-6dc4b4f24413

Feature/#255 페이지 선택할때 화면 벗어나가지 않도록 수정
